/*
 * generated by Xtext
 */
package org.jsstl.xtext.formulas.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.wizard.IProjectCreator;
import org.jsstl.xtext.formulas.ui.wizard.CustomJSSTLProjectCreator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SSTLSpecificationUiModule extends org.jsstl.xtext.formulas.ui.AbstractSSTLSpecificationUiModule {
	public SSTLSpecificationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return CustomJSSTLProjectCreator.class;
	}
	
	
}
