/*
* generated by Xtext
*/
package org.jsstl.xtext.formulas;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SSTLSpecificationStandaloneSetup extends SSTLSpecificationStandaloneSetupGenerated{

	public static void doSetup() {
		new SSTLSpecificationStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

