/*
 * generated by Xtext
 */
package org.jsstl.xtext.formulas;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SSTLSpecificationRuntimeModule extends org.jsstl.xtext.formulas.AbstractSSTLSpecificationRuntimeModule {

}
